# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/nietzsche/Downloads/IDA Pro 7.0/idasdk70/idasdk70/ldr/ida-libbfd-loader"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/nietzsche/Downloads/IDA Pro 7.0/idasdk70/idasdk70/ldr/ida-libbfd-loader"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nietzsche/Downloads/IDA Pro 7.0/idasdk70/idasdk70/ldr/ida-libbfd-loader/CMakeFiles" "/Users/nietzsche/Downloads/IDA Pro 7.0/idasdk70/idasdk70/ldr/ida-libbfd-loader/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nietzsche/Downloads/IDA Pro 7.0/idasdk70/idasdk70/ldr/ida-libbfd-loader/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ida-libbfd-loader

# Build rule for target.
ida-libbfd-loader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ida-libbfd-loader
.PHONY : ida-libbfd-loader

# fast build rule for target.
ida-libbfd-loader/fast:
	$(MAKE) -f CMakeFiles/ida-libbfd-loader.dir/build.make CMakeFiles/ida-libbfd-loader.dir/build
.PHONY : ida-libbfd-loader/fast

ida-libbfd-loader.o: ida-libbfd-loader.cpp.o

.PHONY : ida-libbfd-loader.o

# target to build an object file
ida-libbfd-loader.cpp.o:
	$(MAKE) -f CMakeFiles/ida-libbfd-loader.dir/build.make CMakeFiles/ida-libbfd-loader.dir/ida-libbfd-loader.cpp.o
.PHONY : ida-libbfd-loader.cpp.o

ida-libbfd-loader.i: ida-libbfd-loader.cpp.i

.PHONY : ida-libbfd-loader.i

# target to preprocess a source file
ida-libbfd-loader.cpp.i:
	$(MAKE) -f CMakeFiles/ida-libbfd-loader.dir/build.make CMakeFiles/ida-libbfd-loader.dir/ida-libbfd-loader.cpp.i
.PHONY : ida-libbfd-loader.cpp.i

ida-libbfd-loader.s: ida-libbfd-loader.cpp.s

.PHONY : ida-libbfd-loader.s

# target to generate assembly for a file
ida-libbfd-loader.cpp.s:
	$(MAKE) -f CMakeFiles/ida-libbfd-loader.dir/build.make CMakeFiles/ida-libbfd-loader.dir/ida-libbfd-loader.cpp.s
.PHONY : ida-libbfd-loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ida-libbfd-loader"
	@echo "... ida-libbfd-loader.o"
	@echo "... ida-libbfd-loader.i"
	@echo "... ida-libbfd-loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

